.TH lwaddr 1 "September 2015" Linux "Linux Audio Manual"
.SH NAME
lwaddr \- LiveWire stream address lookup tool

.SH SYNOPSIS
lwaddr <\fIsrc-num\fP>|<\fIip-addr\fP> 

.SH DESCRIPTION
\fBlwaddr\fP is a command-line tool for looking up LiveWire stream
addresses or numbers.

.SH AUTHOR
Fred Gleason <fredg@paravelsystems.com>
.SH SEE ALSO
.BR lwcp (1), lwrp (1)









