.TH lwrp 1 "September 2015" Linux "Linux Audio Manual"
.SH NAME
lwrp \- Command monitor for LiveWire Routing Protocol (LWRP)

.SH SYNOPSIS
lwrp [OPTIONS] <\fIhost-name\fP>[:<\fIport\fP>]

.SH DESCRIPTION
\fBlwrp\fP is a command-line monitor that can be used to monitor and
originate LiveWire Routing Protocol (LWRP) messages with LiveWire
devices.  The default LWRP port number is 93.

.SH OPTIONS
.TP
.B --color=\fBon\fP|\fBoff\fP
Turn protocol colorization \fBon\fP or \fBoff\fP (default is \fBon\fP).

.SH AUTHOR
Fred Gleason <fredg@paravelsystems.com>
.SH SEE ALSO
.BR lwaddr (1), lwcp   (1)









